jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build -x test
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
        ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
        buildNumber: ${{ github.run_number }}
        githubRef: ${{ github.ref }}
      name: Publish Packages to Sonotype
      run: ./gradlew -Pversion="${githubRef#refs/tags/}" -PbuildNumber="${buildNumber}"
        sign publishMavenPublicationToSonatypeRepository
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
name: Release Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle-release.yml
